---
source_image_list:
  - source_image_name: "rhde-lptp.bcnconsulting.com:5000/image1-rhel84"
    source_image_tag: "1.0.2"
  - source_image_name: "rhde-lptp.bcnconsulting.com:5000/image2-rhel84"
    source_image_tag: "2.1.0"
debug_enabled: false
...
