---
### DHCP server variables
dhcp_server: "192.168.50.1"
dhcp_subnet: "192.168.50.0"
dhcp_netmask: "255.255.255.0"
dhcp_interface: "enp2s0"
dhcp_routers: "192.168.50.1"
dhcp_dns_servers: "192.168.50.1"
dhcp_range_start: "192.168.50.100"
dhcp_range_end: "192.168.50.200"
dhcp_ipxe_tftp: "192.168.50.1"
dhcp_ipxe_architecture_type: "00:07"

### Variables to define the filename that will be delivered depend on:
### dhcp_system_boot_mode:  EFI || BIOS
### dhcp_network_boot_protocol: ipxe||httpboot
dhcp_filename_efi_default_httpboot: "http://{{ dhcp_server }}/rhel84/EFI/BOOT/BOOTX64.EFI"
dhcp_filename_efi_default_ipxe: "rhel84/EFI/BOOT/BOOTX64.EFI"
dhcp_filename_bios_default_ipxe: "ipxe/devices-image.ipxe"
dhcp_filename_bios_image1_ipxe:  "ipxe/devices-image1.ipxe"
dhcp_filename_efi_image1_ipxe: rhel84/device-image1/EFI/BOOT/BOOTX64.EFI
dhcp_filename_efi_image1_httpboot: http://{{ dhcp_server }}/rhel84/device-image1/EFI/BOOT/BOOTX64.EFI
dhcp_filename_bios_image2_ipxe:  "ipxe/device-image2.ipxe"
dhcp_filename_efi_image2_ipxe: rhel84/device-image2/EFI/BOOT/BOOTX64.EFI
dhcp_filename_efi_image2_httpboot: http://{{ dhcp_server }}/rhel84/device-image2/EFI/BOOT/BOOTX64.EFI
...
