---
- name: Reboot Remote Host
  hosts: edge_servers
  tasks:
    - name: Reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

    - name: Ping the target host
      ping:

    - debug:
        msg: "Reboot done"
...
